In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('./PhonePe_Yearly_Transactions.csv')
data.head()

           Date                   Paid to  Amount Paid by
0  Apr 01, 2021                Raja Ahmed  1050.0     NaN
1  Apr 05, 2021  Bank Account XXXXXXX9420     1.0  XX4182
2  Apr 05, 2021                ******7527  2000.0  XX4182
3  Apr 07, 2021                Raja Ahmed  1050.0  XX4182
4  Apr 12, 2021                  Flipkart   325.0  XX4182

In [5]:
data.columns

Index(['Date', 'Paid to', 'Amount', 'Paid by'], dtype='object')

In [6]:
data.shape

(1737, 4)

In [7]:
data.isnull()

       Date  Paid to  Amount  Paid by
0     False    False   False     True
1     False    False   False    False
2     False    False   False    False
3     False    False   False    False
4     False    False   False    False
...     ...      ...     ...      ...
1732  False    False   False    False
1733  False    False   False    False
1734  False    False   False    False
1735  False    False   False    False
1736  False    False   False    False

[1737 rows x 4 columns]

In [8]:
data.isnull().sum()

Date         0
Paid to      0
Amount       8
Paid by    240
dtype: int64

In [9]:
#find the total amount spent
total_amount_spent = data['Amount'].sum()
print("Total amount spent:", total_amount_spent)

Total amount spent: 256704.02000000002

In [13]:
# Total amount paid to 
total_amount_paid_to_one = data[data['Paid to']=="Minuwara Store"]["Amount"].sum()
total_amount_paid_to_two = data[data['Paid to']=='Mrs Minuwara Begum']['Amount'].sum()
print("Total amount paid to:\n", total_amount_paid_to_one)
print("Total amount paid to:\n", total_amount_paid_to_two)

Total amount paid to:
 902.0
Total amount paid to:
 467.0

In [ ]:
# paid amount to nurjahan 
total_amount_paid_to_nurjahan = data[data['Paid to']=="Nurjahan Store"]["Amount"].sum()
total_amount_paid_to_bapukon = data[data['Paid to']=="BAPKAN ALI"]["Amount"].sum()
total_amount_paid_to_bapukonn = data[data['Paid to']=="NURJAHAN STORE"]["Amount"].sum()
print("Total amount paid to Nurjahan:", total_amount_paid_to_nurjahan)
print("Total amount paid to Nurjahan:", total_amount_paid_to_bapukon)
print("Total amount paid to Nurjahan:", total_amount_paid_to_bapukonn)

Total amount paid to Nurjahan: 9587.0
Total amount paid to Nurjahan: 397.0

In [16]:
# paid to yousuf through phone pay
total_amount_paid_to_yousuf = data[data['Paid to']=="Yusuf Ali"]["Amount"].sum()
print("Total amount paid to Yousuf:", total_amount_paid_to_yousuf)

Total amount paid to Yousuf: 1414.0

In [17]:
# Paid to baba store
total_amount_paid_to_baba = data[data['Paid to']=="Baba Store"]["Amount"].sum()
print("Total amount paid to Baba:", total_amount_paid_to_baba)

Total amount paid to Baba: 4968.0

In [18]:
# Paid to Bobby Lodge
total_amount_paid_to_bobby = data[data['Paid to']=="Boby lodge"]["Amount"].sum()
print("Total amount paid to Bobby:", total_amount_paid_to_bobby)

Total amount paid to Bobby: 1400.0